server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddd_wms?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver